modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"
[[mods]]
modId="zombie_players"
version="${file.jarVersion}"
displayName="Zombie Players"
authors="Corosus"
description='''
Brainssss
'''
