modLoader="javafml"
loaderVersion="[35,)"
license="All Rights Reserved"
[[mods]]
modId="zombie_players"
version="${file.jarVersion}"
displayName="Zombie Players"
authors="Corosus"
description='''
Brainssss
'''

[[dependencies.zombie_players]]
modId="coroutil"
mandatory=true
versionRange="[1.18.1-1.2.38,1.18.1-1.5)"
ordering="NONE"
side="BOTH"